package com.boss.ipv6ddns.ui.theme

import androidx.compose.ui.graphics.Color

// Material You-ish fallback palette
val BluePrimary = Color(0xFF1E88E5)
val BlueOnPrimary = Color(0xFFFFFFFF)
val BluePrimaryContainer = Color(0xFFD0E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BlueSecondary = Color(0xFF535F70)
val BlueOnSecondary = Color(0xFFFFFFFF)
val BlueSecondaryContainer = Color(0xFFD7E3F7)
val BlueOnSecondaryContainer = Color(0xFF101C2B)
val BlueTertiary = Color(0xFF6B5778)
val BlueTertiaryContainer = Color(0xFFF2DAFF)
val BlueOnTertiaryContainer = Color(0xFF251431)
val BlueError = Color(0xFFBA1A1A)
val BlueOnError = Color(0xFFFFFFFF)
val BlueErrorContainer = Color(0xFFFFDAD6)
val BlueOnErrorContainer = Color(0xFF410002)
val BlueBackground = Color(0xFFFDFCFF)
val BlueOnBackground = Color(0xFF1A1C1E)
val BlueSurface = Color(0xFFFDFCFF)
val BlueOnSurface = Color(0xFF1A1C1E)
val BlueSurfaceVariant = Color(0xFFDFE2EB)
val BlueOnSurfaceVariant = Color(0xFF43474E)
val BlueOutline = Color(0xFF73777F)

val BluePrimaryDark = Color(0xFF9DCAFF)
val BlueOnPrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFFD0E4FF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val BlueOnSecondaryDark = Color(0xFF253140)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val BlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD6BEE4)
val BlueOnTertiaryDark = Color(0xFF3B2948)
val BlueTertiaryContainerDark = Color(0xFF523F5F)
val BlueOnTertiaryContainerDark = Color(0xFFF2DAFF)
val BlueErrorDark = Color(0xFFFFB4AB)
val BlueOnErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val BlueOnErrorContainerDark = Color(0xFFFFDAD6)
val BlueBackgroundDark = Color(0xFF1A1C1E)
val BlueOnBackgroundDark = Color(0xFFE2E2E6)
val BlueSurfaceDark = Color(0xFF1A1C1E)
val BlueOnSurfaceDark = Color(0xFFE2E2E6)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val BlueOnSurfaceVariantDark = Color(0xFFC3C6CF)
val BlueOutlineDark = Color(0xFF8D9199)
